Allow health check errand to be configured to fail
[#138107577]

Signed-off-by: Simon Jones <sijones@pivotal.io>

diff --git a/jobs/health-check/templates/health-check.sh.erb b/jobs/health-check/templates/health-check.sh.erb
--- a/jobs/health-check/templates/health-check.sh.erb
+++ b/jobs/health-check/templates/health-check.sh.erb
@@ -1,5 +1,10 @@
 #!/bin/bash -e
 
+<% if p('health-check.systest-failure-override') %>
+echo "System test errand failure override detected"
+exit 1
+<% end %>
+
 redis_host="<%= link('redis').instances[0].address %>"
 redis_password="<%= link('redis').p('redis.password') %>"
 
